### ISSUE TITLE
New version is broken (Win10)

### ISSUE THREAD

**Issue by LordMike** [Genbox/CygwinContextMenu#3]
The recent version (with manifest & single-user mode) seems to be broken.
When the handler is registered in Windows 10, and run, it prompts the following dialog:

![image](https://cloud.githubusercontent.com/assets/1027111/10263009/d91de594-69de-11e5-8cc3-6878bd3eec49.png)

The previous version works without issue still.
Procmon shows that in the old version, `HKCR\Directory\background\shell\opencygwin\command` is accessed successfully, while the same path results in `NAME NOT FOUND` in the new version (when registered for all users).

**Comment by Genbox** [comment]
Tested on 3 different Windows 10 installations, including a 100% fresh install with all updates. Works fine on all 3.

**Comment by Genbox** [comment]
It sounds like an UAC issue. Registry virtualization perhaps? The thing is, RV should be disabled when using requireAdministrator manifest as well as on 64bit applications. Or perhaps you have an antivirus that blocks the association?

**Comment by jjiimm64** [comment]
Its win10 that is broken, I wont every use win10.  If they ever sunset windows7 I will migrate completely to linux :)
